In [19]:
import pandas as pd
import numpy as np
import re

courses_df = pd.read_csv('all_slu_courses.csv')
courses_df

,Course Title,Credits,Prerequisites,Concurrent Enrollment,Major
0,AEP 0100 - Writing and Grammar Level 1: Beginner,Credit(s): 4 Credits,NaN,NaN,Academic English Program (AEP)
1,AEP 0120 - Reading and Vocabulary Level 1: Beg...,Credit(s): 4 Credits,NaN,NaN,Academic English Program (AEP)
2,AEP 0130 - Listening and Speaking Level 1: Beg...,Credit(s): 4 Credits,NaN,NaN,Academic English Program (AEP)
3,AEP 0200 - Writing and Grammar Level 2: High B...,Credit(s): 4 Credits,NaN,NaN,Academic English Program (AEP)
4,AEP 0220 - Reading and Vocabulary Level 2: Hig...,Credit(s): 4 Credits,NaN,NaN,Academic English Program (AEP)
...,...,...,...,...,...
6393,WGST 6790X - Feminist Approaches to Social Wor...,Credit(s): 3 Credits,NaN,NaN,Women's and Gender Studies (WGST)
6394,WGST 6833 - Employment Discrimination,Credit(s): 3 Credits,NaN,NaN,Women's and Gender Studies (WGST)
6395,WGST 6875 - Family Law,Credit(s): 3 Credits,NaN,NaN,Women's and Gender Studies (WGST)
6396,WGST 6930 - Special Topics: Women Studies,Credit(s): 3 Credits (Repeatable for credit),NaN,NaN,Women's and Gender Studies (WGST)
6397,WGST 6980 - Independent Study,Credit(s): 1 or 3 Credits (Repeatable for credit),NaN,NaN,Women's and Gender Studies (WGST)

In [20]:
def extract_course_number_without_regex(title):
    parts = title.split()
    for part in parts:
        if part.isdigit() and len(part) == 4:
            return int(part)
    return None

courses_df['Course Number'] = courses_df['Course Title'].apply(extract_course_number_without_regex)
filtered_courses_df = courses_df[courses_df['Course Number'] < 5000]
filtered_courses_df = filtered_courses_df.drop(columns=['Course Number'])

In [21]:
def split_course_title(title):
    parts = title.split(" - ", 1)
    if len(parts) == 2:
        return parts[0], parts[1]
    return title, ""  # In case there is no " - " in the title

filtered_courses_df[['Course Name', 'Course Details']] = filtered_courses_df['Course Title'].apply(lambda x: pd.Series(split_course_title(x)))
filtered_courses_df = filtered_courses_df.drop(columns=['Course Title'])

In [22]:
import re

def process_credits(credits):
    repeatable = "Repeatable for credit" in credits
    # Extract all numeric values, including ranges (ie. 1-3 Credits)
    numeric_parts = re.findall(r'\d+', credits)
    # Convert numeric parts to integers and find the maximum value
    numeric_values = [int(part) for part in numeric_parts]
    max_credits = max(numeric_values) if numeric_values else None
    return max_credits, repeatable

filtered_courses_df[['Number of Credits', 'Repeatable']] = filtered_courses_df['Credits'].apply(lambda x: pd.Series(process_credits(x)))
filtered_courses_df['Repeatable'] = filtered_courses_df['Repeatable'].astype(bool)
filtered_courses_df = filtered_courses_df.drop(columns=['Credits'])

In [24]:
filtered_courses_df['Concurrent Enrollment'] = ~filtered_courses_df['Concurrent Enrollment'].isna()

In [4]:
prerequisites_cleaned = filtered_courses_df.query("'Course Name' == 'CSCI 2050'")['Prerequisites']
prerequisites_cleaned

NameError: name 'filtered_courses_df' is not defined

In [25]:
filtered_courses_df.head(50)

,Prerequisites,Concurrent Enrollment,Major,Course Name,Course Details,Number of Credits,Repeatable
0,NaN,False,Academic English Program (AEP),AEP 0100,Writing and Grammar Level 1: Beginner,4,False
1,NaN,False,Academic English Program (AEP),AEP 0120,Reading and Vocabulary Level 1: Beginner,4,False
2,NaN,False,Academic English Program (AEP),AEP 0130,Listening and Speaking Level 1: Beginner,4,False
3,NaN,False,Academic English Program (AEP),AEP 0200,Writing and Grammar Level 2: High Beginner,4,False
4,NaN,False,Academic English Program (AEP),AEP 0220,Reading and Vocabulary Level 2: High Beginner,4,False
5,NaN,False,Academic English Program (AEP),AEP 0230,Listening and Speaking Level 2: High Beginner,4,False
6,NaN,False,Academic English Program (AEP),AEP 0250,English through Service Level 2: High Beginner,1,False
7,NaN,False,Academic English Program (AEP),AEP 0300,Writing and Grammar Level 3: Intermediate,4,False
8,NaN,False,Academic English Program (AEP),AEP 0310,Exploring Cultures Level 3: Intermediate,3,False
10,NaN,False,Academic English Program (AEP),AEP 0320,Reading and Vocabulary Level 3: Intermediate,3,False
12,NaN,False,Academic English Program (AEP),AEP 0330,Listening and Speaking Level 3: Intermediate,4,False
14,NaN,False,Academic English Program (AEP),AEP 0350,English through Service Level 3: Intermediate,1,False
15,NaN,False,Academic English Program (AEP),AEP 0400,Writing and Grammar Level 4: High Intermediate,4,False
17,NaN,False,Academic English Program (AEP),AEP 0410,Contemporary Issues Level 4: High Intermediate,3,False
19,NaN,False,Academic English Program (AEP),AEP 0411,"People, Places, Connections: An Introduction t...",3,False
21,NaN,False,Academic English Program (AEP),AEP 0420,Reading and Vocabulary Level 4: High Intermediate,3,False
23,NaN,False,Academic English Program (AEP),AEP 0430,Listening & Speaking Level 4: High Intermediate,4,False
25,NaN,False,Academic English Program (AEP),AEP 0450,English through Service Level 4: High Intermed...,1,False
26,NaN,False,Academic English Program (AEP),AEP 0500,Writing and Grammar Level 5: Low Advanced,4,False
27,NaN,False,Academic English Program (AEP),AEP 0510,Intercultural Communication Level 5: Low Advanced,3,False
28,NaN,False,Academic English Program (AEP),AEP 0520,Reading and Vocabulary Level 5: Low Advanced,3,False
29,NaN,False,Academic English Program (AEP),AEP 0530,Listening and Speaking Level 5: Low Advanced,4,False
30,NaN,False,Academic English Program (AEP),AEP 0930,Special Topics,4,False
31,NaN,False,Academic English Program (AEP),AEP 1410,"People, Places, Connections: An Introduction t...",3,False
32,"BIZ 1000, BIZ 1001",False,Accounting (ACCT),ACCT 2200,Financial Accounting,3,False
33,"ACCT 2200, BIZ 1002",False,Accounting (ACCT),ACCT 2220,Accounting for Decision Making,3,False
34,NaN,False,Accounting (ACCT),ACCT 2930,Special Topics,3,True
35,NaN,False,Accounting (ACCT),ACCT 2980,Independent Study,3,True
36,"ACCT 2200, BIZ 1002",False,Accounting (ACCT),ACCT 3060,Accounting and Business Consulting,3,False
37,ACCT 2200,False,Accounting (ACCT),ACCT 3110,Financial Reporting I,3,False
38,ACCT 2200,False,Accounting (ACCT),ACCT 3160,International Accounting for Global Organizations,3,False
39,"ACCT 2220, BTM 2500",False,Accounting (ACCT),ACCT 3220,Cost Management,3,False
40,NaN,False,Accounting (ACCT),ACCT 3930,Special Topics,3,True
41,NaN,False,Accounting (ACCT),ACCT 3980,Independent Study,3,True
42,ACCT 3110,False,Accounting (ACCT),ACCT 4110,Financial Reporting II,3,False
43,ACCT 4110,False,Accounting (ACCT),ACCT 4200,Accounting Data Analytics,3,False
44,"ACCT 3110, BTM 2000",False,Accounting (ACCT),ACCT 4250,Accounting Information Systems,3,False
45,ACCT 3110,False,Accounting (ACCT),ACCT 4300,Federal Income Tax I,3,False
46,"ACCT 4110, ACCT 4250",True,Accounting (ACCT),ACCT 4400,Auditing,3,False
47,"ACCT 3110, BTM 2500, BIZ 3000",False,Accounting (ACCT),ACCT 4910,Accounting Internship,3,True
48,NaN,False,Accounting (ACCT),ACCT 4930,Special Topics,3,True
49,NaN,False,Accounting (ACCT),ACCT 4980,Independent Study,3,True
70,NaN,False,Aerospace Engineering (AENG),AENG 1001,Introduction to Aerospace & Mechanical Enginee...,1,False
71,NaN,False,Aerospace Engineering (AENG),AENG 1002,Computer-Aided Engineering Design,1,False
72,"AENG 1002, MENG 1002, PHYS 1610",True,Aerospace Engineering (AENG),AENG 2000,Intro to Aeronautics & Astron,3,False
73,NaN,False,Aerospace Engineering (AENG),AENG 2020,Introduction to Aero and Astro Engineering,1,False
74,"CORE 1000, CORE 1500",True,Aerospace Engineering (AENG),AENG 2910,Co-op with Industry,3,True
75,NaN,False,Aerospace Engineering (AENG),AENG 2930,Special Topics,3,True
76,NaN,False,Aerospace Engineering (AENG),AENG 2980,Independent Study,3,True
77,"AENG 2000, AENG 2020",False,Aerospace Engineering (AENG),AENG 3000,Performance,3,False

In [26]:
out_fileName = 'cleaned_slu_courses.csv'
filtered_courses_df.to_csv(out_fileName, index=False)

In [36]:
courses_df = pd.read_csv('cleaned_slu_courses.csv')

def clean_prerequisites(prereq_str):
    if pd.isnull(prereq_str):
        return None
    # Remove quotation marks
    prereq_str = prereq_str.replace('"', '').replace("'", "")
    return prereq_str

courses_df['Prerequisites'] = courses_df['Prerequisites'].apply(clean_prerequisites)

['AEP\xa00100' 'AEP\xa00120' 'AEP\xa00130' ... 'WGST\xa04930'
 'WGST\xa04960' 'WGST\xa04980']

In [62]:
courses_df = pd.read_csv('cleaned_slu_courses.csv')


# Define a function to clean the prerequisites
def clean_prerequisites(prereq_str):
    if pd.isnull(prereq_str):
        return None
    # Remove quotation marks
    prereq_str = prereq_str.replace('"', '').replace("'", "")
    # Split by comma
    prereq_list = prereq_str.split(',')
    # Strip whitespace and remove duplicates
    prereq_list = list(dict.fromkeys([prereq.strip() for prereq in prereq_list]))
    # Join back into a single string with commas
    return ', '.join(prereq_list)

# Apply the cleaning function to the 'Prerequisites' column
courses_df['Prerequisites'] = courses_df['Prerequisites'].apply(clean_prerequisites)

In [63]:
out_fileName = 'cleaned_slu_courses2.csv'
courses_df.to_csv(out_fileName, index=False)

In [7]:
import numpy as np
import pandas as pd

course = 'CSCI 2100'
courses_df = pd.read_csv('cleaned_slu_courses2.csv')

prerequisites_cleaned = courses_df.query('Course Name' == 'CSCI 2050')['Prerequisites']
prerequisites_cleaned


# # Replace NaN values with an empty string
# courses_df['Prerequisites'] = courses_df['Prerequisites'].replace(np.nan, '')

# # Function to clean and split prerequisites
# def clean_prerequisites(prerequisite_string):
#     if prerequisite_string:
#         # Replace non-breaking spaces with regular spaces
#         cleaned_string = prerequisite_string.replace('\xa0', ' ')
#         # Split the string into a list if there are multiple prerequisites
#         prerequisites_list = [prereq.strip() for prereq in cleaned_string.split(',')]
#         return prerequisites_list
#     return []

# # Apply the function to the 'Prerequisites' column
# courses_df['Prerequisites'] = courses_df['Prerequisites'].apply(clean_prerequisites)

# # Retrieve the cleaned prerequisites for 'CSCI 2100'

# course = 'CSCI 2050'
# # prerequisites_cleaned = courses_df[courses_df['Course Name'] == course]['Prerequisites'].values
# # prerequisites_cleaned = courses_df.loc[courses_df['Course Name'] == course, 'Prerequisites']
# # prerequisites_cleaned = courses_df.query("'Course Name' == 'CSCI 2050'")['Prerequisites']
# prerequisites_cleaned = courses_df[courses_df['Course Name'] == course].groupby('Course Name')['Prerequisites'].apply(list)

# print(prerequisites_cleaned)

ValueError: expr must be a string to be evaluated, <class 'bool'> given

In [ ]:
import numpy as np
import pandas as pd

course = 'CSCI 2100'
file_path = 'cleaned_slu_courses2.csv'

# Load the CSV file
courses_df = pd.read_csv(file_path)

# Replace NaN values with an empty string
courses_df['Prerequisites'] = courses_df['Prerequisites'].replace(np.nan, '')

# Clean the 'Course Name' column by removing leading/trailing spaces and non-breaking spaces
courses_df['Course Name'] = courses_df['Course Name'].str.strip().str.replace('\xa0', ' ')

# Function to clean and split prerequisites
def clean_prerequisites(prerequisite_string):
    if prerequisite_string:
        # Replace non-breaking spaces with regular spaces
        cleaned_string = prerequisite_string.replace('\xa0', ' ')
        # Split the string into a list if there are multiple prerequisites
        prerequisites_list = [prereq.strip() for prereq in cleaned_string.split(',')]
        return prerequisites_list
    return []

# Apply the function to the 'Prerequisites' column
courses_df['Prerequisites'] = courses_df['Prerequisites'].apply(clean_prerequisites)

# Clean the target course name
cleaned_course = course.strip().replace('\xa0', ' ')

# Retrieve the cleaned prerequisites for the target course
prerequisites_cleaned = courses_df[courses_df['Course Name'] == cleaned_course]['Prerequisites']

# Check if the prerequisites series is empty
if not prerequisites_cleaned.empty:
    prerequisites_list = prerequisites_cleaned.values[0]
    print(prerequisites_list)
else:
    print(f"No prerequisites found for course {cleaned_course}")